// apps-script/Platforms.gs and apps-script/AdminPlatforms.html, generated
// from assets/js/platforms.js (the link-experience registry), so the
// publisher, the admin and the site share one list.
// Written by tools/sync-admin.mjs; tests/platforms.test.mjs checks they're current.

import * as registry from '../../assets/js/platforms.js';

// the source may be checked out with CRLF (Windows); the copies use LF
const source = fn => fn.toString().replace(/\r\n/g, '\n');

export function platformsGs({ PLATFORMS, SCENES, experienceKey, resolveExperience } = registry) {

  return [
    '/* Generated by tools/sync-admin.mjs from assets/js/platforms.js. Do not edit by hand. */',
    '',
    `var PLATFORM_SCENES = ${JSON.stringify(SCENES)};`,
    '',
    `var PLATFORMS = ${JSON.stringify(PLATFORMS, null, 2)};`,
    '',
    // private in Apps Script (a trailing _ keeps google.script.run away)
    source(experienceKey).replace('function experienceKey(', 'function experienceKey_('),
    '',
    source(resolveExperience)
      .replace('function resolveExperience(', 'function resolveExperience_(')
      .replace(/experienceKey\(/g, 'experienceKey_('),
    ''
  ].join('\n');

}

/* the admin's copy: the link editor lists the choices and shows what
   «تلقائي» resolves to, with the very same function */
export function platformsAdminHtml({ PLATFORMS, experienceKey, resolveExperience } = registry) {

  return [
    '<!-- Generated by tools/sync-admin.mjs from assets/js/platforms.js. Do not edit by hand. -->',
    '<script>',
    '(function () {',
    `var PLATFORMS = ${JSON.stringify(PLATFORMS)};`,
    source(experienceKey),
    source(resolveExperience),
    'window.ADMIN_PLATFORMS = PLATFORMS;',
    'window.adminResolveExperience = function (link) { return resolveExperience(link, PLATFORMS); };',
    '})();',
    '</script>',
    ''
  ].join('\n');

}
