// apps-script/AdminPlatforms.html, generated from assets/js/platforms.js:
// the admin's copy of the link-experience registry. The link editor lists
// the choices from it and shows what «تلقائي» opens, with the very same
// resolveExperience the site and the publisher use.
// Written by tools/sync-admin.mjs; tests/platforms.test.mjs checks it's current.

import * as registry from '../../assets/js/platforms.js';

export function platformsAdminHtml({ PLATFORMS, experienceKey, resolveExperience } = registry) {

  return [
    '<!-- Generated by tools/sync-admin.mjs from assets/js/platforms.js. Do not edit by hand. -->',
    '<script>',
    '(function () {',
    `var PLATFORMS = ${JSON.stringify(PLATFORMS)};`,
    experienceKey.toString(),
    resolveExperience.toString(),
    'window.ADMIN_PLATFORMS = PLATFORMS;',
    'window.adminResolveExperience = function (link) { return resolveExperience(link, PLATFORMS); };',
    '})();',
    '</script>',
    ''
  ].join('\n').replace(/\r\n/g, '\n');   // the same file from a CRLF checkout

}
