// apps-script/Platforms.gs, generated from assets/js/platforms.js (the
// link-experience registry), so the publisher and the site share one list.
// Written by tools/sync-admin.mjs; tests/platforms.test.mjs checks it's current.

import * as registry from '../../assets/js/platforms.js';

export function platformsGs({ PLATFORMS, SCENES, experienceKey, resolveExperience } = registry) {

  return [
    '/* Generated by tools/sync-admin.mjs from assets/js/platforms.js. Do not edit by hand. */',
    '',
    `var PLATFORM_SCENES = ${JSON.stringify(SCENES)};`,
    '',
    `var PLATFORMS = ${JSON.stringify(PLATFORMS, null, 2)};`,
    '',
    // private in Apps Script (a trailing _ keeps google.script.run away)
    experienceKey.toString().replace('function experienceKey(', 'function experienceKey_('),
    '',
    resolveExperience.toString()
      .replace('function resolveExperience(', 'function resolveExperience_(')
      .replace(/experienceKey\(/g, 'experienceKey_('),
    ''
  ].join('\n').replace(/\r\n/g, '\n');   // a CRLF checkout must generate the same file

}
