// Builds the official admin page (GitHub Pages, /admin/) from the SAME files
// the Apps Script admin uses, so there is one admin, not two:
//
//   apps-script/Admin.html          → the panel markup in admin/index.html
//                                     (wrapped by tools/source/admin-index.html)
//   apps-script/AdminStyles.html    → admin/admin.css (+ the site's own fonts)
//   apps-script/Admin{Icons,Platforms,Script,Page,Content,Media,Items,
//                     Home,Preview}.html → admin/admin-app.js
//
// The <script>/<style> wrappers are stripped; the order is Admin.html's
// include order. Hand-written (not generated): admin/boot.js (Google
// sign-in + the API transport), admin/config.js (the public settings),
// admin/gate.css, admin/preview-guard.js.
//
// Run after changing any apps-script/Admin*.html:  cd tools && npm run build-admin
// (npm run sync runs it too). tests/refine-b.test.mjs fails when admin/ is stale.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ROOT } from './lib/gs.mjs';

const NOTE = 'Generated by tools/build-admin.mjs from apps-script/Admin*.html. Do not edit by hand: change apps-script/ and run `cd tools && npm run build-admin`.';

// the site's own fonts (the Apps Script admin loads Cairo from Google Fonts;
// this page's security policy allows only its own origin)
const FONTS = `@font-face {
  font-family: "Cairo";
  font-style: normal;
  font-weight: 400 800;
  font-display: swap;
  src: url("../assets/fonts/cairo-arabic.woff2") format("woff2");
  unicode-range: U+0020, U+00A0, U+0600-06FF, U+0750-077F, U+0870-088E, U+0890-0891, U+0897-08E1, U+08E3-08FF, U+200C-200E, U+2010-2011, U+204F, U+2E41, U+FB50-FDFF, U+FE70-FE74, U+FE76-FEFC;
}

@font-face {
  font-family: "Cairo";
  font-style: normal;
  font-weight: 400 800;
  font-display: swap;
  src: url("../assets/fonts/cairo-latin.woff2") format("woff2");
  unicode-range: U+0021-0040, U+0051-0052, U+005B-0060, U+007B-007E, U+00AB, U+00BB, U+00D7, U+2013-2014, U+2018-2019, U+201C-201D, U+2022, U+2026;
}

@font-face {
  font-family: "Cairo";
  font-style: normal;
  font-weight: 400 800;
  font-display: swap;
  src: url("../assets/fonts/cairo-latin-letters.woff2") format("woff2");
  unicode-range: U+0041-0050, U+0053-005A, U+0061-007A;
}

@font-face {
  font-family: "Aref Ruqaa";
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url("../assets/fonts/aref-ruqaa-arabic.woff2") format("woff2");
  unicode-range: U+0020-0021, U+00A0, U+0600-06FF, U+0750-077F, U+0870-088E, U+0890-0891, U+0897-08E1, U+08E3-08FF, U+200C-200E, U+2010-2011, U+204F, U+2E41, U+FB50-FDFF, U+FE70-FE74, U+FE76-FEFC;
}
`;

const read = path => readFileSync(`${ROOT}${path}`, 'utf8').replace(/\r\n/g, '\n');

/* the one <tag>…</tag> a partial is made of (an HTML comment may come first) */
function unwrap(name, tag) {

  const text = read(`apps-script/${name}.html`);
  const match = new RegExp(`^\\s*(?:<!--[\\s\\S]*?-->\\s*)?<${tag}>\\n?([\\s\\S]*?)\\n?</${tag}>\\s*$`).exec(text);

  if (!match || match[1].includes(`<${tag}>`) || match[1].includes('<?')) {
    throw new Error(`apps-script/${name}.html: expected exactly one <${tag}> block and no scriptlets`);
  }

  return match[1];

}

export function buildAdmin() {

  const admin = read('apps-script/Admin.html');
  const includes = [...admin.matchAll(/<\?!= include_\('(\w+)'\) \?>/g)].map(m => m[1]);

  if (includes[0] !== 'AdminStyles' || includes.length < 3) {
    throw new Error('apps-script/Admin.html: expected AdminStyles first, then the scripts');
  }

  // the panel markup: everything in <body> before the first script include
  const body = /<body>\n([\s\S]*?)\n\s*<\?!= include_\('AdminIcons'\) \?>/.exec(admin);
  if (!body) throw new Error('apps-script/Admin.html: the <body> layout changed; update tools/build-admin.mjs');
  const shell = body[1].replace(/\s+$/, '');

  if (/<\?|<script|\son[a-z]+=|\sstyle=/.test(shell)) {
    throw new Error('apps-script/Admin.html: the panel markup must have no scriptlets, scripts, inline handlers or styles');
  }

  // the only inline code in Admin.html is the start call; boot.js makes it after sign-in
  const inline = [...admin.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1].trim());
  if (inline.length !== 1 || inline[0] !== 'A.start();') {
    throw new Error('apps-script/Admin.html: unexpected inline script; boot.js only knows A.start()');
  }

  const scripts = includes.slice(1).map(name => `/* ---------- ${name}.html ---------- */\n${unwrap(name, 'script')}\n`);

  const index = read('tools/source/admin-index.html')
    .replace('{{GENERATED}}', NOTE)
    .replace('{{SHELL}}', shell.split('\n').map(line => (line ? '  ' + line : line)).join('\n'));

  return {
    'admin/index.html': index,
    'admin/admin.css': `/* ${NOTE} */\n\n${FONTS}\n${unwrap('AdminStyles', 'style')}\n`,
    'admin/admin-app.js': `/* ${NOTE} */\n\n${scripts.join('\n')}`
  };

}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {

  const files = buildAdmin();
  const check = process.argv.includes('--check');
  const stale = [];

  for (const [path, text] of Object.entries(files)) {
    let current = null;
    try { current = read(path); } catch { /* new file */ }
    if (current === text) continue;
    stale.push(path);
    if (!check) writeFileSync(`${ROOT}${path}`, text);
  }

  if (check && stale.length) {
    console.error(`admin/ is stale: ${stale.join(', ')}. Run: cd tools && npm run build-admin`);
    process.exit(1);
  }

  console.log(check ? 'admin/ is current.' : stale.length ? `written: ${stale.join(', ')}` : 'admin/ was already current.');

}
