// Generates apps-script/AdminIcons.html from the public site's icon set, so
// the admin preview shows exactly the icons visitors will see. Also checks
// that Content.gs ICON_NAMES and icons.js LINK_ICON_NAMES agree.
//
// Run after changing assets/js/icons.js: npm run sync

import { writeFileSync } from 'node:fs';
import { loadGs, ROOT } from './lib/gs.mjs';

// icons.js parses markup with a <template>; give it a tiny stand-in
globalThis.document = { createElement: () => ({ content: {} }) };

const { iconSvg, LINK_ICON_NAMES } = await import('../assets/js/icons.js');

const gs = loadGs(['Content.gs']);
const serverNames = [...gs.ICON_NAMES];

const missing = serverNames.filter(n => !LINK_ICON_NAMES.includes(n));
const extra = LINK_ICON_NAMES.filter(n => !serverNames.includes(n));

if (missing.length || extra.length) {
  console.error('ICON_NAMES mismatch.', { onlyInContentGs: missing, onlyInIconsJs: extra });
  process.exit(1);
}

// admin-only interface icons (same 24px line style)
const ADMIN_EXTRA = {
  'chevron-up': '<path d="m6 15 6-6 6 6"/>',
  edit: '<path class="duo" d="M4 20h4L19 9a2.8 2.8 0 0 0-4-4L4 16Z"/><path d="m13.5 6.5 4 4"/>',
  trash: '<path d="M4 7h16M10 11v6M14 11v6"/><path class="duo" d="M6 7l1 12.5A1.5 1.5 0 0 0 8.5 21h7a1.5 1.5 0 0 0 1.5-1.5L18 7"/><path d="M9 7V4.5A1.5 1.5 0 0 1 10.5 3h3A1.5 1.5 0 0 1 15 4.5V7"/>'
};

const names = [...LINK_ICON_NAMES, 'phone', 'close', 'chevron', 'alert', 'sparkle', 'megaphone'];
const icons = Object.fromEntries(names.map(name => [name, iconSvg(name)]));

for (const [name, body] of Object.entries(ADMIN_EXTRA)) {
  icons[name] = `<svg class="icon icon--line" viewBox="0 0 24 24" aria-hidden="true" focusable="false">${body}</svg>`;
}

writeFileSync(`${ROOT}apps-script/AdminIcons.html`,
`<!-- Generated by tools/sync-admin.mjs from assets/js/icons.js. Do not edit by hand. -->
<script>
window.ADMIN_ICONS = ${JSON.stringify(icons, null, 1)};
</script>
`);

console.log(`AdminIcons.html written (${Object.keys(icons).length} icons); ICON_NAMES in sync.`);
